"""Agrega numero_erogacion a erogacion

Revision ID: 017384836820
Revises: 811ca99d0b5a
Create Date: 2026-02-10 14:27:50.414432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017384836820'
down_revision = '811ca99d0b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erogacion', schema=None) as batch_op:
        batch_op.alter_column('numero_erogacion',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erogacion', schema=None) as batch_op:
        batch_op.alter_column('numero_erogacion',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
