"""Refactorizacion de tablas intermedas Becario e Investigador x Proyecto

Revision ID: 0f592219ef32
Revises: 7b76a0efb3b5
Create Date: 2026-02-19 14:13:54.030214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f592219ef32'
down_revision = '7b76a0efb3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('becarioxproyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=True))

    with op.batch_alter_table('investigadorxproyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=True))

    with op.batch_alter_table('trabajos_revista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajos_revista', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    with op.batch_alter_table('investigadorxproyecto', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    with op.batch_alter_table('becarioxproyecto', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###
