"""Esquema inicial

Revision ID: 144cc08f8bc9
Revises: 
Create Date: 2026-01-16 18:34:09.718087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144cc08f8bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_apellido', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_utn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuente_financiamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_utn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mail', sa.Text(), nullable=False),
    sa.Column('nombre_unidad_academica', sa.Text(), nullable=False),
    sa.Column('objetivo_desarrollo', sa.Text(), nullable=False),
    sa.Column('nombre_sigla_grupo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programa_incentivos_investigador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_contrato_transferencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_dedicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_erogacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_formacion_becario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_proyecto_investigacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_registro_propiedad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrasena', sa.String(length=128), nullable=False),
    sa.Column('mail', sa.String(length=120), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('articulo_divulgacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=False),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('becario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('nombre_apellido', sa.String(length=120), nullable=False),
    sa.Column('tipo_formacion_id', sa.Integer(), nullable=False),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.Column('fuente_financiamiento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_financiamiento_id'], ['fuente_financiamiento.id'], ),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['tipo_formacion_id'], ['tipo_formacion_becario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentacion_bibliografica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('editorial', sa.Text(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_utn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamiento_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.Text(), nullable=False),
    sa.Column('descripcion_breve', sa.Text(), nullable=False),
    sa.Column('fecha_incorporacion', sa.Date(), nullable=False),
    sa.Column('monto_invertido', sa.Float(), nullable=False),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erogacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('egresos', sa.Float(), nullable=False),
    sa.Column('ingresos', sa.Float(), nullable=False),
    sa.Column('tipo_erogacion_id', sa.Integer(), nullable=True),
    sa.Column('fuente_financiamiento_id', sa.Integer(), nullable=True),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_financiamiento_id'], ['fuente_financiamiento.id'], ),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['tipo_erogacion_id'], ['tipo_erogacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_apellido', sa.String(length=120), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('tipo_dedicacion_id', sa.Integer(), nullable=True),
    sa.Column('categoria_utn_id', sa.Integer(), nullable=True),
    sa.Column('programa_incentivos_id', sa.Integer(), nullable=True),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_utn_id'], ['categoria_utn.id'], ),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['programa_incentivos_id'], ['programa_incentivos_investigador.id'], ),
    sa.ForeignKeyConstraint(['tipo_dedicacion_id'], ['tipo_dedicacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_apellido', sa.String(length=120), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('tipo_personal_id', sa.Integer(), nullable=False),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['tipo_personal_id'], ['tipo_personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planificacion_grupo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_utn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_patente_grupo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_articulo', sa.Text(), nullable=False),
    sa.Column('organismo_registrante', sa.Text(), nullable=False),
    sa.Column('tipo_registro_id', sa.Integer(), nullable=False),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['tipo_registro_id'], ['tipo_registro_propiedad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencia_socio_productiva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adoptante', sa.Text(), nullable=False),
    sa.Column('demandante', sa.Text(), nullable=False),
    sa.Column('descripcion_actividad', sa.Text(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tipo_contrato_id', sa.Integer(), nullable=True),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['tipo_contrato_id'], ['tipo_contrato_transferencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_grupo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_visita', sa.Text(), nullable=False),
    sa.Column('razon', sa.Text(), nullable=False),
    sa.Column('procedencia', sa.Text(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividad_y_catedra_posgrado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso', sa.Text(), nullable=False),
    sa.Column('institucion', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('grado_academico', sa.Text(), nullable=False),
    sa.Column('rol_actividad', sa.Text(), nullable=False),
    sa.Column('investigador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investigador_id'], ['investigador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autorxlibro',
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['autor.id'], ),
    sa.ForeignKeyConstraint(['id_libro'], ['documentacion_bibliografica.id'], ),
    sa.PrimaryKeyConstraint('id_autor', 'id_libro')
    )
    op.create_table('participacion_relevante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.Text(), nullable=False),
    sa.Column('forma_participacion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('investigador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investigador_id'], ['investigador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyecto_investigacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_proyecto', sa.Integer(), nullable=False),
    sa.Column('nombre_proyecto', sa.Text(), nullable=False),
    sa.Column('descripcion_proyecto', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dificultades_proyecto', sa.Text(), nullable=True),
    sa.Column('tipo_proyecto_id', sa.Integer(), nullable=False),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.Column('fuente_financiamiento_id', sa.Integer(), nullable=True),
    sa.Column('planificacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_financiamiento_id'], ['fuente_financiamiento.id'], ),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['planificacion_id'], ['planificacion_grupo.id'], ),
    sa.ForeignKeyConstraint(['tipo_proyecto_id'], ['tipo_proyecto_investigacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajo_reunion_cientifica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo_trabajo', sa.Text(), nullable=False),
    sa.Column('nombre_reunion', sa.Text(), nullable=False),
    sa.Column('ciudad', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('tipo_reunion_cientifica', sa.Text(), nullable=False),
    sa.Column('investigador_id', sa.Integer(), nullable=True),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['investigador_id'], ['investigador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo_trabajo')
    )
    op.create_table('becarioxproyecto',
    sa.Column('id_becario', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_becario'], ['becario.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto_investigacion.id'], ),
    sa.PrimaryKeyConstraint('id_becario', 'id_proyecto')
    )
    op.create_table('distincion_recibida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('proyecto_investigacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_investigacion_id'], ['proyecto_investigacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigadorxproyecto',
    sa.Column('id_investigador', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_investigador'], ['investigador.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto_investigacion.id'], ),
    sa.PrimaryKeyConstraint('id_investigador', 'id_proyecto')
    )
    op.create_table('trabajos_revista',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo_trabajo', sa.Text(), nullable=False),
    sa.Column('nombre_revista', sa.Text(), nullable=False),
    sa.Column('editorial', sa.Text(), nullable=False),
    sa.Column('issn', sa.Text(), nullable=False),
    sa.Column('pais', sa.Text(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto_investigacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajos_revista')
    op.drop_table('investigadorxproyecto')
    op.drop_table('distincion_recibida')
    op.drop_table('becarioxproyecto')
    op.drop_table('trabajo_reunion_cientifica')
    op.drop_table('proyecto_investigacion')
    op.drop_table('participacion_relevante')
    op.drop_table('autorxlibro')
    op.drop_table('actividad_y_catedra_posgrado')
    op.drop_table('visita_grupo')
    op.drop_table('transferencia_socio_productiva')
    op.drop_table('registros_patente_grupo')
    op.drop_table('planificacion_grupo')
    op.drop_table('personal')
    op.drop_table('investigador')
    op.drop_table('erogacion')
    op.drop_table('equipamiento_grupo')
    op.drop_table('documentacion_bibliografica')
    op.drop_table('becario')
    op.drop_table('articulo_divulgacion')
    op.drop_table('usuario')
    op.drop_table('tipo_registro_propiedad')
    op.drop_table('tipo_proyecto_investigacion')
    op.drop_table('tipo_personal')
    op.drop_table('tipo_formacion_becario')
    op.drop_table('tipo_erogacion')
    op.drop_table('tipo_dedicacion')
    op.drop_table('tipo_contrato_transferencia')
    op.drop_table('programa_incentivos_investigador')
    op.drop_table('grupo_utn')
    op.drop_table('fuente_financiamiento')
    op.drop_table('categoria_utn')
    op.drop_table('autor')
    # ### end Alembic commands ###
