"""empty message

Revision ID: 2793f050bc2e
Revises: 7c7e8466af38
Create Date: 2026-03-06 19:28:39.330922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2793f050bc2e'
down_revision = '7c7e8466af38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigador_historial_horas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_historial_horas_investigador'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigador_historial_horas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_historial_horas_investigador'), ['investigador_id', 'fecha_inicio'])

    # ### end Alembic commands ###
