"""empty message

Revision ID: 3079a82eb61d
Revises: 473310c32aa6
Create Date: 2026-03-06 15:01:43.659700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3079a82eb61d'
down_revision = '473310c32aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('becario_historial_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('becario_id', sa.Integer(), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['becario_id'], ['becario.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('becario_id', 'fecha_inicio', name='uq_historial_horas_becario')
    )
    op.create_table('investigador_historial_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigador_id', sa.Integer(), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['investigador_id'], ['investigador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigador_id', 'fecha_inicio', name='uq_historial_horas_investigador')
    )
    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_prorrogacion', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.drop_column('fecha_prorrogacion')

    op.drop_table('investigador_historial_horas')
    op.drop_table('becario_historial_horas')
    # ### end Alembic commands ###
