"""Agregar unique a tipo_proyecto.nombre

Revision ID: 32828be7a7e0
Revises: 144cc08f8bc9
Create Date: 2026-01-21 15:22:36.056150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32828be7a7e0'
down_revision = '144cc08f8bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_proyecto_investigacion')
    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('tipo_proyecto_investigacion', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tipo_proyecto_nombre', ['nombre'])

    with op.batch_alter_table('trabajos_revista', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajos_revista', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tipo_proyecto_investigacion', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tipo_proyecto_nombre', type_='unique')

    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=False)

    op.create_table('_alembic_tmp_proyecto_investigacion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo_proyecto', sa.INTEGER(), nullable=False),
    sa.Column('nombre_proyecto', sa.TEXT(), nullable=False),
    sa.Column('descripcion_proyecto', sa.TEXT(), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.Column('dificultades_proyecto', sa.TEXT(), nullable=True),
    sa.Column('tipo_proyecto_id', sa.INTEGER(), nullable=False),
    sa.Column('grupo_utn_id', sa.INTEGER(), nullable=True),
    sa.Column('fuente_financiamiento_id', sa.INTEGER(), nullable=True),
    sa.Column('planificacion_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_financiamiento_id'], ['fuente_financiamiento.id'], ),
    sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id'], ),
    sa.ForeignKeyConstraint(['planificacion_id'], ['planificacion_grupo.id'], ),
    sa.ForeignKeyConstraint(['tipo_proyecto_id'], ['tipo_proyecto_investigacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
