"""Campo fecha actualizado en erogacion

Revision ID: 328677093490
Revises: 0f592219ef32
Create Date: 2026-02-19 15:23:16.599657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328677093490'
down_revision = '0f592219ef32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentacion_bibliografica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=False))

    with op.batch_alter_table('erogacion', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erogacion', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('documentacion_bibliografica', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
