"""Grupo id not null en documentacion

Revision ID: 532f587fe448
Revises: 8281a55a976f
Create Date: 2026-02-19 16:49:49.824002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532f587fe448'
down_revision = '8281a55a976f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentacion_bibliografica', schema=None) as batch_op:
        batch_op.alter_column('grupo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentacion_bibliografica', schema=None) as batch_op:
        batch_op.alter_column('grupo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
