"""empty message

Revision ID: 5e701930950a
Revises: 2793f050bc2e
Create Date: 2026-03-06 19:42:42.840061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e701930950a'
down_revision = '2793f050bc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('becario_historial_horas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_historial_horas_becario'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('becario_historial_horas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_historial_horas_becario'), ['becario_id', 'fecha_inicio'])

    # ### end Alembic commands ###
