"""agrego fechas a personal

Revision ID: 64742ac92bb0
Revises: 017384836820
Create Date: 2026-02-10 23:15:36.384908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64742ac92bb0'
down_revision = '017384836820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###
