"""Agregue el campo Fecha a las entidades faltantes

Revision ID: 7b76a0efb3b5
Revises: b3311ea10160
Create Date: 2026-02-17 16:40:04.214969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b76a0efb3b5'
down_revision = 'b3311ea10160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erogacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erogacion', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
