"""empty message

Revision ID: 7c7e8466af38
Revises: 3079a82eb61d
Create Date: 2026-03-06 15:02:34.200234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7e8466af38'
down_revision = '3079a82eb61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.drop_column('fecha_prorrogacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_prorrogacion', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
