"""agrego nro de erogacion

Revision ID: 811ca99d0b5a
Revises: 
Create Date: 2026-02-10 14:09:37.801954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811ca99d0b5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erogacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_erogacion', sa.Integer(), nullable=False))

    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('tipo_proyecto_investigacion', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tipo_proyecto_nombre', ['nombre'])

    with op.batch_alter_table('trabajos_revista', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajos_revista', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tipo_proyecto_investigacion', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tipo_proyecto_nombre', type_='unique')

    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('erogacion', schema=None) as batch_op:
        batch_op.drop_column('numero_erogacion')

    # ### end Alembic commands ###
