"""elimino fechas de personal

Revision ID: 8f64d985b4fc
Revises: de1ee2f21a54
Create Date: 2026-02-11 01:33:34.831983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f64d985b4fc'
down_revision = 'de1ee2f21a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
