"""Added Audit fields to more models

Revision ID: 9cdae99e79ad
Revises: 61496a28b39f
Create Date: 2026-02-26 06:43:02.243838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cdae99e79ad'
down_revision = '61496a28b39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo_divulgacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_articulo_divulgacion_usuario', 'usuario', ['deleted_by'], ['id'])
        batch_op.create_foreign_key('fk_articulo_divulgacion_usuario', 'usuario', ['created_by'], ['id'])

    with op.batch_alter_table('becario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_becario_usuario', 'usuario', ['deleted_by'], ['id'])
        batch_op.create_foreign_key('fk_becario_usuario', 'usuario', ['created_by'], ['id'])

    with op.batch_alter_table('distincion_recibida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_distincion_recibida_usuario', 'usuario', ['deleted_by'], ['id'])
        batch_op.create_foreign_key('fk_distincion_recibida_usuario', 'usuario', ['created_by'], ['id'])

    with op.batch_alter_table('investigador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_investigador_usuario', 'usuario', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_investigador_usuario', 'usuario', ['deleted_by'], ['id'])

    with op.batch_alter_table('participacion_relevante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_participacion_relevante_usuario', 'usuario', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_participacion_relevante_usuario', 'usuario', ['deleted_by'], ['id'])

    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_personal_usuario', 'usuario', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_personal_usuario', 'usuario', ['deleted_by'], ['id'])

    with op.batch_alter_table('visita_grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_visita_grupo_usuario', 'usuario', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_visita_grupo_usuario', 'usuario', ['deleted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visita_grupo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('activo')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('participacion_relevante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('activo')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('investigador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('distincion_recibida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('activo')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('becario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('articulo_divulgacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('activo')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
