"""Agregar campo primer_login a usuario

Revision ID: a1b2c3d4e5f6
Revises: f8d7e6c5b4a3
Create Date: 2026-02-24 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f8d7e6c5b4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primer_login', sa.Boolean(), nullable=False, server_default='1'))
    
    # Actualizar usuarios existentes a primer_login = False (asumimos que ya han iniciado sesión)
    op.execute("UPDATE usuario SET primer_login = 0 WHERE primer_login = 1")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('primer_login')
    # ### end Alembic commands ###
