"""elimino fechas de personal

Revision ID: de1ee2f21a54
Revises: e7cac7f10bfe
Create Date: 2026-02-11 00:48:13.430694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1ee2f21a54'
down_revision = 'e7cac7f10bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###
