"""agrego fechas a personal

Revision ID: e7cac7f10bfe
Revises: 64742ac92bb0
Create Date: 2026-02-10 23:53:10.945730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cac7f10bfe'
down_revision = '64742ac92bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
