"""Agrega campo activo y ajustes logicos

Revision ID: e95c02b31bb7
Revises: 32828be7a7e0
Create Date: 2026-01-29 15:46:06.702248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95c02b31bb7'
down_revision = '32828be7a7e0'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('becario', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'activo',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )

    with op.batch_alter_table('investigador', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'activo',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )

    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'activo',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('investigador', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('becario', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
