"""Tabla de Becas agregada

Revision ID: eb14143f5f9c
Revises: b02f30003cba
Create Date: 2026-02-23 20:10:27.758403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb14143f5f9c'
down_revision = 'b02f30003cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_beca', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beca_becario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_beca', sa.Integer(), nullable=True),
    sa.Column('id_becario', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('monto_percibido', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_beca'], ['beca.id'], ),
    sa.ForeignKeyConstraint(['id_becario'], ['becario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_destinado', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto_investigacion', schema=None) as batch_op:
        batch_op.drop_column('monto_destinado')

    op.drop_table('beca_becario')
    op.drop_table('beca')
    # ### end Alembic commands ###
