"""Actualizar estructura de visitas - tipo_visita y procedencia

Revision ID: f8d7e6c5b4a3
Revises: eb14143f5f9c
Create Date: 2026-02-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d7e6c5b4a3'
down_revision = 'eb14143f5f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Eliminar todos los datos de la tabla visita_grupo (está vacía de todos modos)
    op.execute('DELETE FROM visita_grupo')
    
    # 2. Recrear la tabla visita_grupo con la nueva estructura
    op.drop_table('visita_grupo')
    
    op.create_table('visita_grupo',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('razon', sa.Text(), nullable=False),
        sa.Column('fecha', sa.Date(), nullable=False),
        sa.Column('procedencia', sa.Text(), nullable=False),  # Nuevo: string en lugar de FK
        sa.Column('tipo_visita_id', sa.Integer(), nullable=False),
        sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id']),
        sa.ForeignKeyConstraint(['tipo_visita_id'], ['tipo_reunion_cientifica.id']),  # Ahora apunta a tipo_reunion_cientifica
        sa.PrimaryKeyConstraint('id')
    )
    
    # 3. Eliminar tabla tipo_visita
    op.drop_table('tipo_visita')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Recrear tabla tipo_visita
    op.create_table('tipo_visita',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre')
    )
    
    # 2. Recrear tabla visita_grupo con estructura anterior
    op.drop_table('visita_grupo')
    
    op.create_table('visita_grupo',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('razon', sa.Text(), nullable=False),
        sa.Column('fecha', sa.Date(), nullable=False),
        sa.Column('procedencia_visita_id', sa.Integer(), nullable=False),
        sa.Column('tipo_visita_id', sa.Integer(), nullable=False),
        sa.Column('grupo_utn_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['grupo_utn_id'], ['grupo_utn.id']),
        sa.ForeignKeyConstraint(['procedencia_visita_id'], ['tipo_reunion_cientifica.id']),
        sa.ForeignKeyConstraint(['tipo_visita_id'], ['tipo_visita.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###
